# Generated by Django 2.2.5 on 2020-05-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'User Profile'},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='org',
            field=models.CharField(blank=True, max_length=128, verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Telephone'),
        ),
    ]
